<script>
export default {
  data: function () {
    return {
      services: [
        {
          image: "Home.png",
          service: "home_and_living",
          name:"Home & Living",
          categories: [
            {name:"Temporary Accommodation", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Property search / advice", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Internet / phone / TV", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Utilities", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Interior design", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Build.png",
          service: "real_estate",
          name:"Real Estate",
          categories: [
            {name:"Market review", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Due diligence / purchase process", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Development / Architecture / engineering", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Priperty Management", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Maintanence / Repairs", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Finance.png",
          service: "finance",
          name:"Finance",
          categories: [
            {name:"Bank account", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Mortgage", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Other financings", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Investment apportunities", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Investment management", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Build.png",
          service: "tax",
          name:"Tax",
          categories: [
            {name:"NIF / Fiscal number", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Structuring Advice", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"NHR Status", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Social security", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Anunual tax returns", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Legal.png",
          service: "legal",
          name:"Legal",
          categories: [
            {name:"Legal representation", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Criminal register certificate", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Document certification / translations", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Contract drafting / reviewing", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Specialist legal advice", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Immigrate.png",
          service: "immigrations",
          name:"Immigrations",
          categories: [
            {name:"Visa (non-EU)", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Residency (EU)", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Golden Visa (non-EU)", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Visa renewal", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Car rental / purchase / maintenance", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Transport.png",
          service: "transport_and_logistics",
          name:"Transport & Logistics",
          categories: [
            {name:"Packers / movers", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Customs", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Vehicle import / divers license", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Car rental / purchase / maintenance", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Storage", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Work.png",
          service: "work_and_business",
          name:"Work & Business",
          categories: [
            {name:"Co-working spaces", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Business incorporation", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Accounting services", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Recruitment / networking", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"PA / problem solving service", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Health.png",
          service: "health",
          name:"Health",
          categories: [
            {name:"Legal representation", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Criminal register certificate", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Document certification / translations", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Contract drafting / reviewing", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Specialist legal advice", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Family.png",
          service: "family",
          name:"Family",
          categories: [
            {name:"Visa (non-EU)", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Residency (EU)", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Golden Visa (non-EU)", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Visa renewal", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Car rental / purchase / maintenance", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
        {
          image: "Lifestyle.png",
          service: "lifestyle",
          name:"Lifestyle",
          categories: [
            {name:"Packers / movers", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Customs", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Vehicle import / divers license", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Car rental / purchase / maintenance", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
            {name:"Storage", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet fringilla ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies. Faucibus magna eget sit aliquet Lorem ipsum dolor sit amet, consectetur adipiscing ut nulla sociis. Ut vitae sit ac odio neque turpis arcu, massa. Et elementum odio non netus cras. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque integer sit nisi morbi vulputate ultricies."},
          ],
        },
      ],
    };
  },
};
</script>
